[package]
name = "race-buffer"
version = "0.1.0"
authors = ["Nicholas Springer <nspringer@auxon.io>"]
edition = "2018"

[dependencies]
crossbeam = {version = "0.7.3", optional = true}
rand = {version = "0.7.3", optional = true}

[features]
default = []
std = ["crossbeam", "rand"]
